# This file was generated by GoReleaser. DO NOT EDIT.
cask "rgboo" do
  version "0.0.1-test"

  on_macos do
    on_arm do
      sha256 "36d015d68266923ab1413095e2ccdea1dd1f27ae9b72869f766aa8a54155b9b7"
      url "https://github.com/nrodd/rgboo/releases/download/v#{version}/rgboo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "800beb9189f2e3900771ce515c960dc872bcc66343d1d1dac79dc4925868a46f"
      url "https://github.com/nrodd/rgboo/releases/download/v#{version}/rgboo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6392244589b16c5c89646c8aa454ad4a0bbfeafd3aa11b928e32b1e0d07e62eb"
      url "https://github.com/nrodd/rgboo/releases/download/v#{version}/rgboo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "472a5b149452f54f35437de8f4257b1ff11c40beae3ce53165e71c14e7d7582a"
      url "https://github.com/nrodd/rgboo/releases/download/v#{version}/rgboo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rgboo"
  desc "Stream the RGBoo live broadcast to your speakers with an animated terminal scene"
  homepage "https://rgboo.com"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
      "yt-dlp",
    ]

  binary "rgboo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rgboo"]
    end
  end

  # No zap stanza required
end
