# This file was generated by GoReleaser. DO NOT EDIT.
cask "rgboo" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "6e694728bd4b176ae9b8b2ba192fb4e7b4f3e1b2a5ebaf2e96737149454cb494"
      url "https://github.com/nrodd/rgboo/releases/download/v#{version}/rgboo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ca0cb86156546c53e2bf2525b15e9f0e22b6b2d594c3dd74a6b67dd031882781"
      url "https://github.com/nrodd/rgboo/releases/download/v#{version}/rgboo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "304216cb7c35d3329665198af7694e492894c189c690c38cc54d3c0d976c28ef"
      url "https://github.com/nrodd/rgboo/releases/download/v#{version}/rgboo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7ba028d8be00affae71bbcb95950c2ee255d56225fb0d64d6482755032bced9f"
      url "https://github.com/nrodd/rgboo/releases/download/v#{version}/rgboo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rgboo"
  desc "Stream the RGBoo live broadcast to your speakers with an animated terminal scene"
  homepage "https://rgboo.com"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
      "yt-dlp",
    ]

  binary "rgboo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rgboo"]
    end
  end

  # No zap stanza required
end
