# This file was generated by GoReleaser. DO NOT EDIT.
cask "rgboo" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "ee3512edb98b90f468de96d1fa72deee996de2cdcf2d30e80d46453f59252fee"
      url "https://github.com/nrodd/rgboo/releases/download/v#{version}/rgboo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cee1aeab1d5164856139a34248483b2101d689108c50b8828fe7de7825dcd189"
      url "https://github.com/nrodd/rgboo/releases/download/v#{version}/rgboo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "439a04121e68e3abaf01899b21f513f8400a10ac16ec2276a84341d615688fd2"
      url "https://github.com/nrodd/rgboo/releases/download/v#{version}/rgboo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "97804858e2449a966d27f3c08a49ff44501ed0ba62a1afde9f284ae0e07b133a"
      url "https://github.com/nrodd/rgboo/releases/download/v#{version}/rgboo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rgboo"
  desc "Stream the RGBoo live broadcast to your speakers with an animated terminal scene"
  homepage "https://rgboo.com"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
      "yt-dlp",
    ]

  binary "rgboo"

  # No zap stanza required
end
